### PR TITLE
Bump OpenJDK

### PR DESCRIPTION
**Pull request by bartbroere**
When I try to build projects using Gradle I'm getting the following error: `Unsupported class file major version 61`

This PR should hopefully fix that.

### CODE REVIEW

**Comment by mindrunner** [comment]
Do we need to fix this in alpine images as well?

**Comment by bartbroere** [comment]
> Do we need to fix this in alpine images as well?

That's probably a good idea as well. I could add it to this PR.

**Comment by mindrunner** [comment]
Yes please. Ate you able to test that? I would be interested in automatically testing this in a github action. Happy for some input :)

**Comment by mindrunner** [comment]
Should be fixed with https://github.com/mindrunner/docker-android-sdk/commit/b694f852de5592c7d764106677e413114f176132

**Pull request closed without merging**
