### PR TITLE
packages: Add Android Q platform

### PR DESCRIPTION
**Pull request by MSF-Jarvis**

### CODE REVIEW

**Comment by mindrunner** [comment]
Hi, thanks for the pull request! Can you please add it to package-list-minimal as well?

**Comment by MSF-Jarvis** [comment]
Will do in a few minutes. I also wanted to update the licenses, should I do it here or in a separate pull request?

**Comment by mindrunner** [comment]
Doesn't matter so much. But rather open another PR. Cheers

**Comment by MSF-Jarvis** [comment]
I've updated this and created #38 for the licenses.

**Pull request merged**
