### PR TITLE
licenses: Add all updated SDK licenses

### PR DESCRIPTION
**Pull request by MSF-Jarvis**

### CODE REVIEW

**Comment by mindrunner** [comment]
Cool, thanks. Can you point to a part of documentation or anything to explain this. I am not able to verify this at the moment, because i am without computer.

**Comment by mindrunner** [comment]
@MSF-Jarvis still on this?

**Comment by MSF-Jarvis** [comment]
> @MSF-Jarvis still on this?

I thought I did reply to the earlier comment, guess the email never went through. Anyways, I'm not sure what documentation you require for this. I simply opened a shell into an `alpine-standalone` container, used ` yes | sdkmanager --licenses` to accept all licenses, then copied the resultant `$ANDROID_HOME/licenses` folder to this repository. If you want I can update the commit description to add this.

**Comment by mindrunner** [comment]
Ok, sounds valid. This was always confusing for me. Let's try.

**Pull request merged**
