### PR TITLE
WIP: Remove dependency on OpenJDK image

### PR DESCRIPTION
**Pull request by oxr463**
Bug: https://github.com/mindrunner/docker-android-sdk/issues/50

### CODE REVIEW

**Comment by oxr463** [comment]
@mindrunner not sure if this was completely working yet; hence the work in progress (WIP) prefix.

**Comment by mindrunner** [comment]
Ouch, did not see that. Sorry. Are you going to test it?

**Comment by mindrunner** [comment]
Do you know if I can make gitlab building GitHub Pull-Requests?

**Comment by oxr463** [comment]
> 
> 
> Do you know if I can make gitlab building GitHub Pull-Requests?

Yes, there is a way to do that. Send me the link to the GitLab project.

**Comment by mindrunner** [comment]
According to the documentation, PRs from forked repos are not built. Do you have other information?

https://gitlab.com/mindrunner/docker-android-sdk

**Pull request merged**
