### PR TITLE
Add Alpine Images

### PR DESCRIPTION
**Pull request by khoanguyen96**
Hey,

This adds in the Alpine based Docker images I mentioned in #12 

Just a couple of things I thought I should mention. I wasn't sure why the build dependencies were disabled:

+ `libc6:i386`
+ `libgcc1:i386`
+ `libncurses5:i386`
+ `libstdc++6:i386`
+ `zlib1g:i386`

I re-enabled them for now... If you would rather not have them enabled. Please tell me :)

Additionally, I moved the Dockerfiles to their respective directories depending on what base image they were based on so: `ubuntu` and `alpine`. This does mean building the Dockerfiles will fail unless the build context is specified differently.

Ex. Building Ubuntu Image
```bash
docker build -t mindrunner/docker-android-sdk . -f ubuntu/Dockerfile
```

Ex. Building Alpine Image
```bash
docker build -t mindrunner/docker-android-sdk . -f alpine/Dockerfile
```

I'll leave the tagging/naming images to you :rocket: 

Additionally, I went ahead and upgraded Ubuntu to version 17.04.

I'm still relatively new to Docker, however, there was a couple of times I ran into an issue about [zombie process reaping](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/) and how su/sudo messed with TTY and etc.

So I went ahead and used `su-exec` for the Alpine image, which means Alpine images use the `tools/entrypoint-alpine.sh` file instead. For this image, I don't think it's that big of a deal...

I used your image as a base and reconfigured it initially to suite my needs. I was reusing the Dockerfile I made for this PR, when i realized I had gradle installed as well. If you would rather not have gradle bloating the image, I can remove it with a future commit! Moreso, I think we could have gradle be opt-in based on a build arg or env??

Thanks!

### CODE REVIEW

**Comment by mindrunner** [comment]
Cool, thanks fir the work! I am in dirtbag mode this week. So might need a
couple of days til i got time to have a look! Cheers

**Comment by mindrunner** [comment]
Hi @khoanguyen96!

I have had a look into your PR now. For me this looks pretty good and I am sure, we can merge it like this. However, I will not do this before first or second January week, because I need to make sure, it will not break things on our Mobile CI. I think, i need to at least update the Dockerfile paths in Dockerhub, and do some testing with the new image(s).

About the Build Dependencies:
I originally removed them, because I use this Image only as Data-Container and not as the container running the build. Since many people seem to use this image now on CircleCi, Bitbucket (and others), I agree that we should put it back in to guarantee maximum compatibility.

Thanks for the contribution and the patience! :)

**Comment by mindrunner** [comment]
I added some comments in the Files! We might need some small changes:

- Can we use su-exec in both images?
- Why do you want to have gradle included in the image?

About File/Folder structure, I am not quite sure. Wasn't satisfied with the original solution either. How about:

./ubuntu/standalone/Dockerfile
./ubuntu/lazydl/Dockerfile
./alpine/standalone/Dockerfile
./alpine/lazydl/Dockerfile

I tried to figure out what naming conventions for Dockerfiles are when using multiple files in the same folder/repo. It seems that it is recommended to not change the Filename and rather use subfolders. I think, we should do the same.

**Comment by khoanguyen96** [comment]
I changed the file/folder structure as you suggested! I agree, it seems like the recommended way is to use subfolders... :+1: 

I also removed gradle as that can be added in via a separate Dockerfile if someone else needs it specifically. (that's probably going to be me :smiley:)

I also added `su-exec` for the Ubuntu image as well. Since there isn't any official ppa or deb to install for `su-exec` I had to use git clone to build it specifically for the Ubuntu image. I hope that's alright.

To Build:

(Ubuntu)
``` bash
# standalone image
docker build -t mindrunner/docker-android-sdk . -f ubuntu/standalone/Dockerfile

# lazydl
docker build -t mindrunner/docker-android-sdk . -f ubuntu/lazydl/Dockerfile
```

(Alpine)
``` bash
# standalone image
docker build -t mindrunner/docker-android-sdk . -f alpine/standalone/Dockerfile

# lazydl
docker build -t mindrunner/docker-android-sdk . -f alpine/lazydl/Dockerfile
```

I'll leave the Docker tagging/naming up to you :)

Thanks!

**Comment by mindrunner** [comment]
Merging this PR now. The original docker tags latest and lazydl are referering to the ubuntu images for now. All other tags will be announced in readme file as soon as images were build successfully! :)
Thanks for the work!

**Comment by mindrunner** [comment]
Quick status update:

I merged the PR and figured out (once again), that docker hub kind of sucks. It does not work with this sort of setup. I need to be able to define a buidl context. I am moving over to docker cloud now.

Posting back here when everything is set up!

**Comment by mindrunner** [comment]
Builds with docker cloud are running smooth. No need to change URLs or something. We have the following tags now:

ubuntu-standalone
ubuntu-lazydl
alpine-standalone
alpine-lazydl
latest
lazydl

"latest" and "lazydl" are pointing to the ubuntu images. No idea if we really need them, but prevents older builds to fail.

**Pull request merged**
