### PR TITLE
Add devcontainer

### PR DESCRIPTION
**Pull request by bartbroere**
I was experimenting with this repository some more, and eventually landed on this way to combine it with the devcontainer spec. Maybe this could be a nice addition.

### CODE REVIEW

**Comment by mindrunner** [comment]
Can you give me more insight / information what for this would be useful? I am not familiar with `devcontainer`.

**Comment by mindrunner** [comment]
@bartbroere would love to merge that, but I feel like I want some insight before. Can you show a use case or sth?

**Comment by bartbroere** [comment]
> @bartbroere would love to merge that, but I feel like I want some insight before. Can you show a use case or sth?

Sorry, bit of a late reply. How I use it is in VS Code (or Github Codespaces) as an environment where everything is set up to build and develop Android apps.

Devcontainers are an isolated environment that can integrate with your IDE. [containers](https://containers.dev/) was a useful resource for me when I was introduced to it.

Personally it works well for me when I'm developing [Capacitor](https://capacitorjs.com/) apps. The universal devcontainer this is based on already has all the tools to do Node development, and the Dockerfile proposed here adds the tooling for Android building.

**Comment by mindrunner** [comment]
merged. would appreciate if you could update the readme with some valuable information about it.

**Comment by mindrunner** [comment]
Unfortunately, the build fails for the devcontainer flavor :(

https://github.com/mindrunner/docker-android-sdk/actions/runs/5649743258/job/15304830163

Are you able to investigate?

**Pull request merged**
