### PR TITLE
strip down to bare minimum, as filed in #92

### PR DESCRIPTION
**Pull request by cs8898**
As in #92 already mentioned, this PR will Strip down the Image to the bare minimum.
Emulator images have to be downloaded separately.

The list is based on an image i use for Flutter development.

### CODE REVIEW

**Comment by mindrunner** [comment]
Thanks for the PR. 
Wouldn't it be handy to have at least one image preinstalled, so that one can use the emulator without downloading an image?

**Comment by cs8898** [comment]
Would be handy, currently i never tested the emulator but during the current project i will test it.

Propably it would be handy to include also the x64 android 33 image (should be running more easily than arm emulation with qemu)

**Comment by mindrunner** [comment]
Yeah, I think for the normal image, we do not need to be super minimalistic. So we can add one of each kind!

**Comment by cs8898** [comment]
Just found that Project
https://github.com/alvr/alpine-android


But i have not found any time to review/test the emulator inside of docker.
What would be the only reason to include the Images

**Comment by mindrunner** [comment]
I think `ubuntu` was never an issue with emulatort, but `alpine` is more tricky because of  the whole `libc` thing

**Comment by mindrunner** [comment]
Decided to be a little bit less radical, see:
https://github.com/mindrunner/docker-android-sdk/commit/edda25a6b0bba7dee42b1955a97d723ed4433208

Would that be sufficient to you?

**Pull request closed without merging**
